MYSQL_CONFIG:
  name: "mysql_config"
  type: "mysql"
  host: "localhost"
  port: 3307
  username: "root"
  password: "123456"
  database: "test"
  entities: "mysql"
  logging: true
  synchronize: true